config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'comments/create'
  resources :projects do
    resources :comments, module: :projects
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks"}
  root to: 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/perk.rb
class Perk < ApplicationRecord
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_rich_text :description
  has_one_attached :thumbnail
  has_many :comments, as: :commentable
  has_many :perks, dependent: :destroy
  accepts_nested_attributes_for :perks, allow_destroy: true, reject_if: proc { |attr| attr['title']
    .blank? }
end

app/models/user.rb
class User < ApplicationRecord
has_person_name
has_many :projects, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
         :validatable, :omniauthable, omniauth_providers: [:stripe_connect]

  def can_receive_payments? 
    uid? && provider? && access_code? && publishable_key?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def new
    
  end

  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.user = current.user
    @comment.save
    redirect_to @commentable, notice: "Your comment was successfully posted"
  end

  private
  
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def stripe_connect
		auth_data = request.env["omniauth.auth"]
		@user = current_user
		if @user.persisted?
			@user.provider = auth_data.provider 
			@user.uid = auth_data.uid
			@user.access_code = auth_data.credentials.token 
			@user.publishable_key = auth_data.info.stripe_publishable_key 
			@user.save

			sign_in_and_redirect @user, event: :authentication
			flash[:notice] = "Stripe Account Created and Connected" if is_navigational_format?
		else
			session["devise.stripe_connect_data"] = request.env["omniauth.auth"]
			redirect_to root_path
		end
	end

	def failure
		redirect_to root_path
	end

end

app/controllers/projects/comments_controller.rb
class Projects::CommentsController < CommentsController
	before_action :set_commentable

	private
	def set_commentable
		@commentable = Project.find(params[:project_id])
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, expect: [:index, :show]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id

    respond_to do |format|
      if @project.save
        # .set(wait_until: @project.expires_at) , change _later
        ExpireProjectJob.perform_now(@project)
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :donation_goal, :description, 
        :thumbnail, perks_attributes: [:id, :_destroy, :title, :amount, :quantity])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def author_of(resource)
		user_signed_in? && resource.user_id == current_user.id
	end

	def admin?
		user_signed_in? && current_user.admin?
	end

	def stripe_url
		"https://connect.stripe.com/oauth/authorize?response_type=code&client_id=
			#{Rails.application.credentials.dig(:stripe, :connect_client_id)}&scope=read_write"
	end

	def stripe_connect_button
		link_to stripe_url, class: "btn-stripe-connect" do
      content_tag :span, "Connect with Stripe"
    end
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects/comments_helper.rb
module Projects::CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comments.html.erb
<p class="text-sm font-semibold text-gray-500 uppercase">Comments</p>
	<% commentable.comments.each do |comment| %>
		<div class="my-4">
			<div class="p-4 leading-normal border rounded shadow">
				<div><strong><%= comment.user.name || comment.user.username %></strong>:</div>
				<%= comment.body %>
			</div>
		</div>
	<% end %>

app/views/comments/_form.html.erb
<%= form_for [commentable, Comment.new] do |f| %>
	<div class="mb-6">
		<%= f.text_area :body, class: "input input-with-border", placeholder: "Add a comment" %>
	</div>
	<% f.submit class: "btn btn-default" %>
<% end %>

app/views/home/index.html.erb
<div class="max-w-lg mx-auto mt-16 text-center">
  <h1 class="mb-4 text-3xl font-black">Welcome to Kickoff Tailwind!</h1>
  <p class="text-lg leading-snug">Use this starting point as a way to quickly set up a new project by generating files, installing gems, and more.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="antialiased">
  <%= render "shared/head" %>
<%# removed from body class font-sans font-normal leading-normal %>
  <body class="text-blue-100 bg-blue-800">
    <%= render "shared/flash_notice" %>
    <%= render "shared/header" %>

    <main class="px-4 lg:px-10">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true, multipart: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation" class="p-6 mb-5 text-red-500 bg-white rounded">
      <h2 class="font-bold text-red-500"><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label :thumbnail, "Project thumbnail", class: "label" %>
    <%= form.file_field :thumbnail %>
  </div>

  <div class="mb-6">
    <%= form.label :title, class: "label" %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :donation_goal, class: "label" %>
    <%= form.text_field :donation_goal, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :description, class: "label" %>
    <%= form.rich_text_area :description, class: "input" %>
  </div>

  <div class="my-10">
    <h3 class="text-2xl">Perks</h3>
    <div data-controller="nested-form">
      <template data-target="nested-form.template">
        <%= form.fields_for :perks, Perk.new, child_index: 'TEMPLATE_RECORD' do |perk| %>
          <%= render "perk_fields", form: perk %>
        <% end %>
      </template>
      <%= form.fields_for :perks do |perk| %>
        <%= render "perk_fields", form: perk %>
      <% end %>

      <div data-target="nested-form.add_perk">
        <%= link_to "Add perk", "#", data: { action: "nested-form#add_association"},
          class: "btn btn-white" %>
      </div>
    </div>
  </div>

  <div class="mb-6">
    <%= form.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/projects/_perk_fields.html.erb
<div class="p-6 mb-4 border rounded nested-fields">

  <%= form.hidden_field :_destroy %>

  <div class="mb-6">
    <%= form.label :title %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :description %>
    <%= form.text_area :description, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :amount, "Subscription amount" %>
    <%= form.text_field :amount, placeholder: "0.00", class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :quantity %>
    <%= form.text_field :quantity, placeholder: "10", class: "input" %>
  </div>

	<%= link_to "Remove", "#", data: { action: "click->nested-form#remove_association" },
		class: "text-white underline text-sm" %>

</div>

app/views/projects/edit.html.erb
<div class="max-w-lg m-auto">
	<h1 class="mb-6 text-3xl font-bold">Editing a Project</h1>

		<%= render 'form', project: @project %>

</div>

app/views/projects/index.html.erb
<div class="flex flex-wrap items-center justify-between">
  <% @projects.each do |project| %>
    <div class="relative w-full p-6 mb-6 border-2 border-blue-700 rounded-lg lg:w-1/4 lg:mr-8">
      <%= image_tag project.thumbnail, class: "rounded h-auto mb-4 w-full max-w-f" if project.thumbnail.present? %>
      <h3 class="font-bold text-2xl mb-2"><%= project.title %></h3>
      <div class="my-1"><%= truncate(strip_tags(project.description.to_s), length: 140) %></div>
      <p><%= project.donation_goal %></p>
      <%= link_to 'View Project', project, class: "btn btn-default inline-block text-center my-2" %>
      <% if author_of(project) %>
      <div class="absolute top-0 right-0 mt-2 mr-2">
        <%= link_to edit_project_path(project) do %>
          <svg class="fill-current text-white opacity-75 w-6 h-6" xmlns="http://www.w3.org/2000/svg" 
            width="24" height="24" viewBox="0 0 24 24"><title>edit</title>
            <path d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 
            0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z"></path></svg>
        <% end %>
        </div>
      <% end %>
    </div>

  <% end %>
</div>

app/views/projects/new.html.erb
<div class="max-w-lg m-auto">
	<h1 class="mb-6 text-3xl font-bold">Create a Project</h1>
	<%= render 'form', project: @project %>
</div>

app/views/projects/show.html.erb
<div class="container relative p-6 mx-auto text-gray-900 bg-white rounded-lg lg:p-10">
  <div class="flex flex-wrap items-center justify-between w-full pb-4 mb-8 border-b-2 border-gray-200">
    <div class="flex flew-wrap items-start justify-between w-full pb-4 mb-4 border-b-2 border-gray-200">
      <div class="flex-1">
        <h1 class="text-3xl font-bold leading-none text-gray-800">
          <%= @project.title %></h1>
          <p class="text-sm italic text-gray-500">Created by <%= @project.user.name || @project.user.username %></p>
      </div>
      <% unless author_of(@project) %>
        <%= link_to "Back this idea", "#", class: "btn btn-default btn-lg lg:w-auto w-full lg:text-left text-center" %>
      <% end %>
      <div class="w-full mb-4 lg:w-1/5 lg:mb-0">
        <p class="m-0 text-xl font-semibold leading-none"><%#= @project.pledged_amount %>$1000</p>
        <p class="text-sm text-gray-500">pledged of <%= number_to_currency(@project.donation_goal) %></p>
      </div>
      <div class="w-full mb-4 lg:w-1/5 lg:mb-0">
        <p class="m-0 text-xl font-semibold leading-none">200</p>
        <p class="text-sm text-gray-500">backers</p>
      </div>
      <div class="w-full mb-4 lg:w-1/5 lg:mb-0">
        <p class="m-0 text-xl font-semibold leading-none">20</p>
        <p class="text-sm text-gray-500">days to go</p>
      </div>
    </div>

    <div class="flex flex-wrap items-start justify-between w-full mb-6">
      <div class="w-full lg:w-3/5">
        <% if @project.thumbnail.present? %>
          <%= image_tag @project.thumbnail, class: "rounded" %>
        <% else %> 
          <div class="flex items-center justify-center p-8 text-center bg-gray-100 rounded">
            <div>
              <p class="text-xs font-bold text-gray-600 uppercase">PROJECT</p>
              <h3 class="text-2xl text-black"><%= @project.title %></h3>
            </div>
          </div>
        <% end %> 
        <div class="my-6">
          <%= render "comments/comments", commentable: @project %>
          <%= render "comments/form", commentable: @project %>
        </div>
      </div>
      <div class="w-full mt-6 lg:pl-10 lg:w-2/5 lg:mt-0">
        <div class="mb-6">
          <p class="text-sm font-semibold text-gray-500 uppercase">Description</p>
          <%= @project.description %>
        </div>
      </div>
    </div>
  </div>


  <% if admin? || author_of(@project) %>
    <div class="absolute top-0 right-0 mt-4 mr-4">
        <%= link_to "Edit", edit_project_path(@project), class: "btn btn-sm btn-outlined btn-default"  %> 
        <%= link_to "Delete", project_path(@project), method: :delete, data: {confirm: "Are you sure?"}, 
          class: "btn btn-sm btn-outlined btn-default" %> 
    </div>
  <% end %> 
  </div>
</div>

app/views/shared/_flash_notice.html.erb
<% flash.each do |type, message| %>
  <% if type == "alert" %>
    <div class="bg-red-500">
      <div class="container px-2 py-4 mx-auto font-sans font-medium text-center 
        text-white"><%= message %></div>
    </div>
  <% end %>
  <% if type == "notice" %>
    <div class="bg-green-500">
      <div class="container px-2 py-4 mx-auto font-sans font-medium text-center 
        text-white"><%= message %></div>
    </div>
  <% end %>
<% end %>

app/views/shared/_head.html.erb
 <head>
  <title>
    <% if content_for?(:title) %>
      <%= yield :title %> |
    <% end %>
    Back my Project
  </title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>
  <%# <%= javascript_packs_with_chunks_tag 'application' %> %>
  <%# <%= stylesheet_packs_with_chunks_tag 'application' %> %>
  <%#= javascript_include_tag 'https://js.stripe.com/v3/', 'data-turbolinks-track': 'reload' %>
</head>

app/views/shared/_header.html.erb
<header class="mb-4">
  <nav class="flex flex-wrap items-center justify-between px-3 py-3 lg:px-10">
    <div class="flex items-center mr-6 flex-no-shrink">
      <%= link_to "Back my Project", root_path, class:"link text-xl tracking-tight font-black" %>
    </div>
    <div class="block lg:hidden">
      <button class="flex items-center px-3 py-2 border border-gray-500 rounded text-grey hover:text-gray-600 hover:border-gray-600">
        <svg class="w-3 h-3 fill-current" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
      </button>
    </div>
    <div class="items-center block w-full text-center lg:flex-1 lg:flex lg:text-left">
      <div class="lg:flex-grow">
        <%= link_to "Add New Project", new_project_path, class: "block mt-4 lg:inline-block lg:mt-0 lg:mr-4 mb-2 lg:mb-0 link" %>
      </div>
      <div class="items-center block w-full mt-2 text-center lg:flex lg:flex-row lg:flex-1 lg:mt-0 lg:text-left lg:justify-end">
        <% if user_signed_in? %>
          <%= link_to "Edit account", edit_user_registration_path, class: "btn btn-default mb-2 lg:mr-2 lg:mb-0 block" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"btn btn-default mb-2 lg:mb-0 block" %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class:"btn btn-default mb-2 lg:mr-2 lg:mb-0 block" %>
          <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-default block" %>
        <% end %>
      </div>
    </div>
  </nav>
</header>